server:
  port: 9009
spring:
  redis:
    host: 212.129.249.243
    port: 6379
  rabbitmq:
    host: 212.129.249.243
    port: 5672
mybatis:
  mapper-locations: classpath*:mybatis/*/*.xml
  type-aliases-package: com.murphy.mall.*.po
  configuration:
    # 下划线驼峰转换
    map-underscope-to-camel-case: true
    lazy-loading-enabled: true
    aggressive-lazy-loading: false
logging:
  pattern:
    console: "%d - %msg%n"
  level:
    org.springframework.web: debug
    com.murphy: debug
security:
  oauth2:
    resource:
      jwt:
        key-uri: http://localhost:9098/oauth/token_key # 如果使用JWT，可以获取公钥用于 token 的验签

mq:
  pay:
    exchange:
      order: exchange.pay.order
    queue:
      order: queue.pay.order
    routing:
      key: routing.pay.order
  order:
    exchange:
      ttl: exchange.order.ttl
      dlx: exchange.order.dlx
    queue:
      ttl: queue.order.ttl
      dlx: queue.order.dlx
    routing:
      ttl: routing.order.ttl
      dlx: routing.order.dlx