server:
  port: 9011

spring:
  redis:
    host: 192.168.2.180
    port: 6379
  jackson:
    default-property-inclusion: always
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8

mybatis-plus:
  mapper-locations: classpath*:mybatis/*/*.xml
  type-aliases-package: com.murphy.mall.*.po
  configuration:
    # 下划线驼峰转换
    map-underscope-to-camel-case: true
    lazy-loading-enabled: true
    aggressive-lazy-loading: false

logging:
  pattern:
    console: "%d - %msg%n"
  level:
    org.springframework.web: debug
    com.murphy: debug

