server:
  port: 9004
logging:
  pattern:
    console: "%d - %msg%n"
  level:
    org.springframework.web: debug
    com.murphy: debug

spring:
  servlet:
    multipart:
      enabled: true
      max-file-size: 10MB
      max-request-size: 20MB

fdfs:
  # 链接超时时间
  connect-timeout: 60
  # 读取时间
  so-timeout: 60
  # 生成缩略图参数
  thumb-image:
    width: 150
    height: 150
  tracker-list: 101.34.225.2:22122